// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdsnfxuarhyhgsxaegim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkc25meHVhcmh5aGdzeGFlZ2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODY2MjAsImV4cCI6MjA2NDA2MjYyMH0.2VXbzZb6WF6OhphRZQ4VD2lphqbTm_X-R_TcHs0lvbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);